name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install, build, and test
      run: |
        npm ci || npm install
        npm run build --if-present
        npm test || echo "npm test unavailable"
        npm update
        git diff package*
      env:
        CI: true
    - name: auto-merge
      if: success()
      uses: ridedott/dependabot-auto-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GitOAUTHToken2 }}
